# Generated by Django 3.2.20 on 2023-08-29 11:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0002_auto_20230819_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True),
        ),
    ]
