# Generated by Django 3.2.20 on 2023-08-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230810_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='products.Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ManyToManyField(to='products.SubCategory'),
        ),
    ]
