# Generated by Django 3.2.20 on 2023-08-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
        ('products', '0003_auto_20230810_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'SubCategories'},
        ),
    ]
